
#app.yaml
application: userapp
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /css
  static_dir: static
- url: /public
  static_dir: static
- url: /.*
  script: Fastie.app



libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
