
#app.yaml
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /images
  static_dir: images

- url: /public
  static_dir: static
- url: /.*
  script: Fastie.app



libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
